/**
 * `/blog` — list all posts ordered by date.
 *
 * Posts come from two sources:
 * 1. Hand-written MDX files in `content/blog/`.
 * 2. Auto-imported release notes (one MDX per session block) from
 *    `docs/revamp/release_notes_pycaret4.md`, generated by the sync
 *    script.
 */
import Link from 'next/link';

import { listContent } from '@/lib/content';

export const metadata = {
  title: 'Blog',
  description: 'Engineering posts, release notes, and announcements.',
};

export default function BlogIndex() {
  const posts = listContent('blog')
    .filter((p) => !!p.frontmatter.date)
    .sort((a, b) =>
      (b.frontmatter.date ?? '').localeCompare(a.frontmatter.date ?? ''),
    );

  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <header>
        <h1 className="text-3xl font-semibold tracking-tight text-ink-900">
          Blog
        </h1>
        <p className="mt-3 text-lg leading-relaxed text-ink-600">
          Engineering posts, release notes, and behind-the-scenes details from
          the PyCaret 4.0 rewrite.
        </p>
      </header>

      {posts.length === 0 ? (
        <p className="mt-12 rounded-xl border border-ink-200 bg-ink-50 p-6 text-sm text-ink-600">
          No posts yet — run <code className="font-mono">npm run sync</code> to
          import release notes from the repo.
        </p>
      ) : (
        <ul className="mt-12 space-y-8">
          {posts.map((post) => (
            <li key={post.href}>
              <Link href={post.href} className="group block">
                <div className="font-mono text-xs text-ink-500">
                  {post.frontmatter.date}
                  {post.frontmatter.tags && post.frontmatter.tags.length > 0 && (
                    <span className="ml-3 inline-flex gap-2">
                      {post.frontmatter.tags.slice(0, 3).map((t) => (
                        <span
                          key={t}
                          className="rounded-full border border-ink-200 px-2 py-0.5 text-[10px] text-ink-600"
                        >
                          {t}
                        </span>
                      ))}
                    </span>
                  )}
                </div>
                <h2 className="mt-1 text-xl font-semibold text-ink-900 transition-colors group-hover:text-accent-700">
                  {post.frontmatter.title}
                </h2>
                {post.frontmatter.description && (
                  <p className="mt-2 text-sm leading-relaxed text-ink-600">
                    {post.frontmatter.description}
                  </p>
                )}
              </Link>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
