"""add llm provider settings and consultations

Revision ID: d582b350c276
Revises: 9f9b7c770df0
Create Date: 2026-04-24 16:28:59.660824+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d582b350c276"
down_revision: str | None = "9f9b7c770df0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_provider_settings",
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("api_key_encrypted", sa.Text(), nullable=True),
        sa.Column("base_url", sa.String(length=512), nullable=True),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "provider", name="uq_llm_provider"),
    )
    with op.batch_alter_table("llm_provider_settings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_llm_provider_settings_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "llm_consultations",
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("experiment_id", sa.String(length=36), nullable=True),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("generated_config_json", sa.JSON(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_consultations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_llm_consultations_experiment_id"), ["experiment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_llm_consultations_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_llm_consultations_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_consultations_type"), ["type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_llm_consultations_workspace_id"), ["workspace_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_consultations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_consultations_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_llm_consultations_type"))
        batch_op.drop_index(batch_op.f("ix_llm_consultations_run_id"))
        batch_op.drop_index(batch_op.f("ix_llm_consultations_project_id"))
        batch_op.drop_index(batch_op.f("ix_llm_consultations_experiment_id"))

    op.drop_table("llm_consultations")
    with op.batch_alter_table("llm_provider_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_provider_settings_workspace_id"))

    op.drop_table("llm_provider_settings")
    # ### end Alembic commands ###
