"""add drift_reports and audit_logs

Revision ID: 0cd9d5ea2e17
Revises: d582b350c276
Create Date: 2026-04-24 19:29:32.002947+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0cd9d5ea2e17"
down_revision: str | None = "d582b350c276"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("workspace_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=8), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.String(length=36), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_target_id"), ["target_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_logs_target_type"), ["target_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_logs_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_logs_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "drift_reports",
        sa.Column("deployment_id", sa.String(length=36), nullable=False),
        sa.Column("baseline_artifact_id", sa.String(length=36), nullable=True),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("drift_score", sa.Float(), nullable=False),
        sa.Column("drift_status", sa.String(length=16), nullable=False),
        sa.Column("feature_drift_json", sa.JSON(), nullable=False),
        sa.Column("prediction_drift_json", sa.JSON(), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["baseline_artifact_id"], ["artifacts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["deployment_id"], ["deployments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("drift_reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_drift_reports_baseline_artifact_id"),
            ["baseline_artifact_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_drift_reports_deployment_id"), ["deployment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_drift_reports_drift_status"), ["drift_status"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("drift_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_drift_reports_drift_status"))
        batch_op.drop_index(batch_op.f("ix_drift_reports_deployment_id"))
        batch_op.drop_index(batch_op.f("ix_drift_reports_baseline_artifact_id"))

    op.drop_table("drift_reports")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_target_type"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_target_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    # ### end Alembic commands ###
