"""add_business_context_to_projects_and_experiments

Revision ID: 0ae61317f298
Revises: e5f6a8b9c0d1
Create Date: 2026-07-21 07:21:40.892545+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae61317f298'
down_revision: str | None = 'e5f6a8b9c0d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.alter_column('window_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('approval_workflows', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('required_approvals',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_context', sa.Text(), nullable=True))

    with op.batch_alter_table('git_repositories', schema=None) as batch_op:
        batch_op.alter_column('default_branch',
               existing_type=sa.VARCHAR(length=128),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('max_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('queue',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('metric_points', schema=None) as batch_op:
        batch_op.alter_column('count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('notebook_sessions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('idle_timeout_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.alter_column('kernel',
               existing_type=sa.VARCHAR(length=64),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_context', sa.Text(), nullable=True))

    with op.batch_alter_table('registered_model_versions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_rmv_promoted_by'))
        batch_op.drop_index(batch_op.f('ix_rmv_registered_model_id'))
        batch_op.drop_index(batch_op.f('ix_rmv_run_id'))
        batch_op.drop_index(batch_op.f('ix_rmv_sha256'))
        batch_op.drop_index(batch_op.f('ix_rmv_status'))
        batch_op.drop_index(batch_op.f('ix_rmv_trial_id'))
        batch_op.create_index(batch_op.f('ix_registered_model_versions_promoted_by'), ['promoted_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_registered_model_versions_registered_model_id'), ['registered_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registered_model_versions_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registered_model_versions_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_registered_model_versions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_registered_model_versions_trial_id'), ['trial_id'], unique=False)

    with op.batch_alter_table('registered_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registered_models_current_version_id'), ['current_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registered_models_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_foreign_key('fk_registered_models_current_version_id', 'registered_model_versions', ['current_version_id'], ['id'], ondelete='SET NULL', use_alter=True)

    with op.batch_alter_table('secrets', schema=None) as batch_op:
        batch_op.alter_column('kind',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.alter_column('is_best',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix__alembic_tmp_trials_status'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__alembic_tmp_trials_status'), ['status'], unique=False)
        batch_op.alter_column('is_best',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)

    with op.batch_alter_table('secrets', schema=None) as batch_op:
        batch_op.alter_column('kind',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'opaque'"),
               existing_nullable=False)

    with op.batch_alter_table('registered_models', schema=None) as batch_op:
        batch_op.drop_constraint('fk_registered_models_current_version_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_registered_models_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_registered_models_current_version_id'))

    with op.batch_alter_table('registered_model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registered_model_versions_trial_id'))
        batch_op.drop_index(batch_op.f('ix_registered_model_versions_status'))
        batch_op.drop_index(batch_op.f('ix_registered_model_versions_sha256'))
        batch_op.drop_index(batch_op.f('ix_registered_model_versions_run_id'))
        batch_op.drop_index(batch_op.f('ix_registered_model_versions_registered_model_id'))
        batch_op.drop_index(batch_op.f('ix_registered_model_versions_promoted_by'))
        batch_op.create_index(batch_op.f('ix_rmv_trial_id'), ['trial_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rmv_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rmv_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_rmv_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rmv_registered_model_id'), ['registered_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rmv_promoted_by'), ['promoted_by'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'staging'"),
               existing_nullable=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('business_context')

    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=False)

    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.alter_column('kernel',
               existing_type=sa.VARCHAR(length=64),
               server_default=sa.text("'python3'"),
               existing_nullable=False)

    with op.batch_alter_table('notebook_sessions', schema=None) as batch_op:
        batch_op.alter_column('idle_timeout_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'1800'"),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'starting'"),
               existing_nullable=False)

    with op.batch_alter_table('metric_points', schema=None) as batch_op:
        batch_op.alter_column('count',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('queue',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'default'"),
               existing_nullable=False)
        batch_op.alter_column('max_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'3'"),
               existing_nullable=False)
        batch_op.alter_column('attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'queued'"),
               existing_nullable=False)

    with op.batch_alter_table('git_repositories', schema=None) as batch_op:
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=False)
        batch_op.alter_column('default_branch',
               existing_type=sa.VARCHAR(length=128),
               server_default=sa.text("'main'"),
               existing_nullable=False)

    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_column('business_context')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=False)

    with op.batch_alter_table('approval_workflows', schema=None) as batch_op:
        batch_op.alter_column('required_approvals',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'pending'"),
               existing_nullable=False)

    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=False)
        batch_op.alter_column('window_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'300'"),
               existing_nullable=False)

    # ### end Alembic commands ###
