/**
 * API-tree loader for the `/reference` route.
 *
 * Reads `content/api-tree.json` (generated by `scripts/gen_api_tree.py`)
 * and exposes typed accessors. The JSON file is committed to the repo
 * for environments that don't run the Python extractor — CI regenerates
 * it on every push.
 */
import fs from 'node:fs';
import path from 'node:path';

import type { SidebarSection } from './content';

const TREE_PATH = path.join(process.cwd(), 'content', 'api-tree.json');

export interface ApiParameter {
  name: string;
  kind: string | null;
  annotation: string | null;
  default: string | null;
}

export interface ApiFunction {
  kind: 'function';
  name: string;
  qualname: string;
  signature: string;
  docstring: string | null;
  parameters: ApiParameter[];
  returns: string | null;
  is_async: boolean;
}

export interface ApiAttribute {
  name: string;
  annotation: string | null;
  value: string | null;
  docstring: string | null;
}

export interface ApiClass {
  kind: 'class';
  name: string;
  qualname: string;
  bases: (string | null)[];
  docstring: string | null;
  methods: ApiFunction[];
  attributes: ApiAttribute[];
}

export interface ApiModule {
  kind: 'module';
  qualname: string;
  docstring: string | null;
  classes: ApiClass[];
  functions: ApiFunction[];
  attributes: ApiAttribute[];
}

let cached: Record<string, ApiModule> | null = null;

export function loadApiTree(): Record<string, ApiModule> {
  if (cached) return cached;
  if (!fs.existsSync(TREE_PATH)) {
    cached = {};
    return cached;
  }
  try {
    const raw = fs.readFileSync(TREE_PATH, 'utf8');
    cached = JSON.parse(raw) as Record<string, ApiModule>;
    return cached;
  } catch (err) {
    console.error('[api-tree] failed to parse content/api-tree.json:', err);
    cached = {};
    return cached;
  }
}

export function listApiModules(): string[] {
  return Object.keys(loadApiTree()).sort();
}

export function getApiModule(qualname: string): ApiModule | null {
  const tree = loadApiTree();
  return tree[qualname] ?? null;
}

export function moduleSlug(qualname: string): string[] {
  // pycaret.classification.foo  →  ['classification', 'foo']
  const parts = qualname.split('.');
  if (parts[0] === 'pycaret') parts.shift();
  return parts;
}

export function buildApiSidebar(): SidebarSection[] {
  const groups = new Map<string, { title: string; href: string; description?: string }[]>();
  for (const qualname of listApiModules()) {
    // First segment after `pycaret` is the section.
    const parts = qualname.split('.');
    const section = parts.length >= 2 ? parts[1] : 'core';
    const sectionKey = sectionLabel(section);
    if (!groups.has(sectionKey)) groups.set(sectionKey, []);
    groups.get(sectionKey)!.push({
      title: qualname.replace(/^pycaret\./, ''),
      href: `/reference/${moduleSlug(qualname).join('/')}`,
    });
  }
  // Stable section ordering.
  const order = [
    'Tasks',
    'Core',
    'Plots',
    'Logging',
    'API',
    'Datasets',
  ];
  return Array.from(groups.entries())
    .map(([title, items]) => ({ title, items }))
    .sort((a, b) => {
      const ai = order.indexOf(a.title);
      const bi = order.indexOf(b.title);
      if (ai === -1 && bi === -1) return a.title.localeCompare(b.title);
      if (ai === -1) return 1;
      if (bi === -1) return -1;
      return ai - bi;
    });
}

function sectionLabel(s: string): string {
  switch (s) {
    case 'classification':
    case 'regression':
    case 'clustering':
    case 'anomaly':
    case 'time_series':
    case 'tasks':
      return 'Tasks';
    case 'core':
      return 'Core';
    case 'plots':
      return 'Plots';
    case 'logging':
      return 'Logging';
    case 'api':
      return 'API';
    case 'datasets':
      return 'Datasets';
    default:
      return s.charAt(0).toUpperCase() + s.slice(1);
  }
}
